### ISSUE TITLE
Error:  cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu:69

### ISSUE THREAD

**Issue by hugski** [karfly/learnable-triangulation-pytorch#122]
I used the config and script in repo, but get errors
python3 train.py \
  --config experiments/human36m/train/human36m_alg.yaml \
  --logdir ./logs

do I miss something? the error shown as below

```
Error:  cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu:69                                     [20/1819]
proj_matricies =  tensor([[[[-1.4988e+03,  3.8582e+02, -3.7966e+01,  1.0524e+06],
          [ 1.8102e+01,  7.1732e+01, -1.5405e+03,  2.1025e+06],
          [-3.9714e-01, -8.9666e-01, -1.9568e-01,  5.5239e+03]],

         [[ 1.2006e+03,  6.9192e+02, -1.1225e+01,  1.2021e+06],
          [ 5.0373e+01, -5.2448e+01, -1.3908e+03,  1.9027e+06],
          [-3.7919e-01,  8.9968e-01, -2.1630e-01,  5.7143e+03]],

         [[-1.4293e+03, -6.5491e+02, -1.1590e+02,  1.0379e+06],
          [ 9.2187e+01,  6.4253e+01, -1.6016e+03,  2.1955e+06],
          [ 3.9936e-01, -8.9338e-01, -2.0586e-01,  5.6433e+03]],

         [[ 9.9540e+02, -2.2333e+02,  4.5852e+01,  7.7565e+05],
          [ 7.4194e+01, -6.7532e+01, -1.0241e+03,  1.4430e+06],
          [ 3.9559e-01,  8.8340e-01, -2.5122e-01,  4.4993e+03]]],


        [[[-1.2926e+03,  6.7588e+01, -6.7602e+01,  2.5579e+06],
          [-3.8979e+01, -2.5831e+01, -1.2337e+03,  2.1989e+06],
          [-4.0661e-01, -8.9314e-01, -1.9226e-01,  5.5574e+03]],

         [[ 8.3010e+02,  4.1885e+02, -7.4889e+00,  3.2571e+05],
          [-8.9558e-01,  3.5003e+01, -9.5285e+02,  1.7192e+06],
          [-3.5386e-01,  9.1053e-01, -2.1382e-01,  5.8183e+03]],

         [[-1.1841e+03, -7.2828e+02, -1.3306e+02,  2.0800e+06],
          [ 1.0340e+02, -1.6753e+01, -1.4201e+03,  2.3762e+06],
          [ 3.8893e-01, -8.9645e-01, -2.1241e-01,  5.5344e+03]],

         [[ 7.3306e+02, -3.7788e+02,  9.2329e+01, -5.3276e+05],
          [ 7.4377e+01, -1.0018e+01, -8.5463e+02,  1.3937e+06],
          [ 3.7304e-01,  8.9226e-01, -2.5440e-01,  4.4216e+03]]]],
       device='cuda:0')
Traceback (most recent call last):
  File "/home/zpf/pose_estimation/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 190, in forward
    confidences_batch=alg_confidences
  File "/home/zpf/pose_estimation/learnable-triangulation-pytorch/mvn/utils/multiview.py", line 180, in triangulate_batch_of_points
    point_3d = triangulate_point_from_multiple_views_linear_torch(proj_matricies_batch[batch_i], points, confidences=confidences)
  File "/home/zpf/pose_estimation/learnable-triangulation-pytorch/mvn/utils/multiview.py", line 165, in triangulate_point_from_multiple_views_linear_torch
    point_3d_homo = -vh[:, 3]
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu:69
```

**Comment by sherrywan** [comment]
I get same errors.
If u solved it?

**Comment by sherrywan** [comment]
I have solved this problem. It is caused by the incompatibility between the torch in requirments and your cuda version.
Uninstall torch and reinstall another one match your cuda version.
